### ISSUE TITLE
CSS3 font definition is not supported

### ISSUE THREAD

**Issue by qhwa** [qhwa/fdlint#18]
for example:

``` css
@font-face {
    font-family: myFirstFont;
    src: url(sansation_light.woff);
}
```

Parsing css like above will cause parsing error right now.
